### ISSUE TITLE
Add support for add/modify/rm AVUs

### ISSUE THREAD

**Issue by irinaColgiu** [wtsi-hgi/python-baton-wrapper#18]

**Comment by irinaColgiu** [comment]
Similar to what this command does:
imeta add -d /seq/1/2/3.bam sample "123" (when I can have multiple attributes with this name, diff. values)
imeta rm -d /seq/1/2/3.bam sample "123"
imeta set -d /seq/1/2/3.bam sample "123" (when I want only 1 attribute sample)

**Comment by colin-nolan** [comment]
From the baton's documentation, it looks like it only provides functionality similar to imeta's `add` and `rm`: it does not appear that the set operation is supported. However, it can be supported with use of more than one baton query.

```
$ baton-metamod --help
Name
    baton-metamod

Synopsis

    baton-metamod [--file <JSON file>] --operation <operation>
                  [--silent] [--unbuffered] [--unsafe]
                  [--verbose] [--version]

Description
    Modifies metadata AVUs on collections and data objects
described in a JSON input file.

    --file        The JSON file describing the data objects and
                  collections. Optional, defaults to STDIN.
    --operation   Operation to perform. One of [add, rem].
                  Required.
    --silent      Silence error messages.
    --unbuffered  Flush print operations for each JSON object.
    --unsafe      Permit unsafe relative iRODS paths.
    --verbose     Print verbose messages to STDERR.
    --version     Print the version number and exit.

```

**Comment by colin-nolan** [comment]
Proposed interface for this feature here:
https://github.com/wtsi-hgi/python-baton-wrapper/blob/3587c80adecd5621ab6d7713a18ab18d923add83/baton/mappers.py#L10

I have also updated the README to give examples of the use:
https://github.com/wtsi-hgi/python-baton-wrapper/blob/3587c80adecd5621ab6d7713a18ab18d923add83/README.md#api

**Comment by irinaColgiu** [comment]
OK, but in this case  the "set" operation won't be atomic, right?

**Comment by irinaColgiu** [comment]
I mean it's useful to have a set operation, but should be emphasized the fact that it won't be atomic. Maybe it would be  useful to have an unset operation for a specific attribute. Is there any way to unset all the AVUs, ie delete all the metadata of a file?

**Comment by irinaColgiu** [comment]
Wouldn't it be better if this:

`def` add(self, irods_entity_path: str, metadata: Union[IrodsMetadata, `Iterable[IrodsMetadata]]):`

were split in 2 methods - add(IrodsMetadata) and add_all(Iterable)?

**Comment by irinaColgiu** [comment]
I am guessing the same applies for remove, right? Though it is not written in the type hint of the input parameter, it is described in the documentation:

`def remove(self, irods_entity_path: str, metadata: Iterable[IrodsMetadata]):`

"Removes the given metadata or collection of metadata from the given iRODS entity."

**Comment by colin-nolan** [comment]
> OK, but in this case the "set" operation won't be atomic, right?

This is correct. However, I can't think of a situation where it would be helpful as the metadata is a shared resource, where there is no support for locking. Therefore it is not possible to guarantee what the state of the metadata is, even after you just did an atomic set operation.

> I mean it's useful to have a set operation, but should be emphasized the fact that it won't be atomic. 

The fact that it won't be transactional is probably more relevant.

> Maybe it would be useful to have an unset operation for a specific attribute. Is there any way to unset all the AVUs, ie delete all the metadata of a file?

I could add a `def remove_all(self, paths: Union[str, Iterable[str]])` method if that would be useful?

> Wouldn't it be better if this:
> `def add(self, irods_entity_path: str, metadata: Union[IrodsMetadata, Iterable[IrodsMetadata]]):`
> were split in 2 methods - add(IrodsMetadata) and add_all(Iterable)?

This wouldn't be in line with other methods in the API, e.g. there are not 2 method: `get_by_path` and `get_by_paths`. We discussed splitting the other methods at the time but concluded that it was clearer and more "Pythonic" to overload the parameters than to ~double the number of methods in the API.

> I am guessing the same applies for remove, right? Though it is not written in the type hint of the input parameter, it is described in the documentation:
> `def remove(self, irods_entity_path: str, metadata: Iterable[IrodsMetadata]):`
> "Removes the given metadata or collection of metadata from the given iRODS entity."

Good spot: I shall correct this.

**Comment by colin-nolan** [comment]
`remove_all` (mentioned in https://github.com/wtsi-hgi/python-baton-wrapper/issues/18#issuecomment-196746891) in not currently in the interface.
