### ISSUE TITLE
Add support for add/modify/rm ACLs

### ISSUE THREAD

**Issue by irinaColgiu** [wtsi-hgi/python-baton-wrapper#19]
Add support for add/modify/rm ACLs, both for groups and users.

**Comment by colin-nolan** [comment]
baton just supports what could be called `set`. Although these operations can be implemented in the wrapper, they would require multiple calls to the underlying baton binaries. e.g. `add` would be implemented by something like:

```
access_control_to_add = AccessControl("owner", "zone", AccessControl.WRITE)
existing_acls = list(irods.data_object.access_control.get_all("data_object_path"))
updated_acls = existing_acls + [access_control_to_add]
irods.data_object.access_control.set("data_object_path", updated_acls)
```

**Comment by colin-nolan** [comment]
How would "modifying" an entity's ACLs differ from doing an `add`/`set`/`rm` operation?

**Comment by colin-nolan** [comment]
Proposed interface for this feature here:
https://github.com/wtsi-hgi/python-baton-wrapper/blob/5288d2499121c7948a72112d09510066e7921a87/baton/mappers.py#L8

I have also updated the README to give examples of the use:
https://github.com/wtsi-hgi/python-baton-wrapper/blob/5288d2499121c7948a72112d09510066e7921a87/README.md

**Comment by colin-nolan** [comment]
Requires https://github.com/wtsi-hgi/test-with-baton/issues/8 and https://github.com/wtsi-hgi/test-with-baton/issues/9 for testing.

**Comment by colin-nolan** [comment]
Testing prerequisites now satisfied.

**Comment by colin-nolan** [comment]
During the implementation of this, I've come to the conclusion that a method called `add` is misleading. This is because an ACL can contain at most one access control for a user at one time. If an `add` operation involves an access control definition for a user, where a definition already exists, the `add` does not increase the number of controls: it replaces the existing one. 

```
access_controls = {x3, y2, z1}
acl_mapper.add(access_controls, x1)
# I would expect {x3, y2, z1, x1} but instead it's {x1, y2, z1}!
```

I also not sure about `rm`/`remove`. To say that an operation removes an access control from the ACL sounds like it de-restricts access to the resource. Instead, it is actually setting an access of a user to none (i.e. it is actually a set operation).

**Comment by irinaColgiu** [comment]
Hmm. With add I agree, it is misleading if what it does is add_or_replace() - how about calling it like that to be more clear?
Regarding remove, from my experience adding an ACL with None will not have the impact of the user actually seeing an ACL with (ic4, No_access), but instead the ACL with (ic4, read) will disappear. If for this to happen you need to internally add an ACL with None, I think this is an implementation detail. Me - as a client -  I don't really care how you implement remove_ACL, as long as the result is: before there is ACL (ic4, read), after: there is no ACL for ic4 there.

**Comment by colin-nolan** [comment]
I agree that a "remove"-like operation should still exist but with a more descriptive name.

@Xophmeister suggested on Slack the use of `grant` and `revoke`.

**Comment by colin-nolan** [comment]
Proposing the use of `get_all`, `add_or_replace`, `set`, `revoke`, `revoke_all`.
