### ISSUE TITLE
Please change irods.data_object.get_by_path(path) to return a data object and not a list

### ISSUE THREAD

**Issue by irinaColgiu** [wtsi-hgi/python-baton-wrapper#21]
Currently  irods.data_object.get_by_path(path) returns a list as result, which is slightly counter-intuitive since one asks for a resource that is unique by definition.
e.g.
In [10]: do = irods.data_object.get_by_path('/humgen/projects/hgi/plot_snps.jpg')
In [11]: type(do)
Out[11]: list

Please change the current implementation so that there is a DataObject returned instead.

**Comment by colin-nolan** [comment]
I have also been burnt by this counter-intuitive "feature". I agree that it should be changed.
