### ISSUE TITLE
irods.data_object.get_by_metadata doesn't return anything

### ISSUE THREAD

**Issue by irinaColgiu** [wtsi-hgi/python-baton-wrapper#22]
It appears that something's wrong with irods.data_object.get_by_metadata() because it doesn't return anything on the few examples I've tried. So in iRODS the data is:
mercury@hgi-serapis-farm3-dev:~$ imeta ls -d /humgen/projects/helic/20140310/HELIC5103047.bam sample_name
AVUs defined for dataObj /humgen/projects/helic/20140310/HELIC5103047.bam:
attribute: sample_name
value: HELIC5103047

and if you run the baton wrapper:
In [7]: sc = SearchCriterion("sample_name", "HELIC5103047", ComparisonOperator.EQUALS)

In [8]: irods.data_object.get_by_metadata(sc, zone='humgen')
Out[8]: []

nothing is returned. And this is also the case for other zones, other attributes:

iRODS:
mercury@hgi-serapis-farm3-dev:~$ imeta ls -d /humgen/projects/helic/20140310/HELIC5103047.bam cohort
AVUs defined for dataObj /humgen/projects/helic/20140310/HELIC5103047.bam:
attribute: cohort
value: HELIC_A
units: 

baton-wrapper:
In [14]: sc3 = SearchCriterion("cohort", "HELIC_A", ComparisonOperator.EQUALS)

In [15]: irods.data_object.get_by_metadata(sc3, zone='humgen')
Out[15]: []

**Comment by irinaColgiu** [comment]
Fixed 4b9bca40f3bf2f9fd83051c4dc2aed7368107f6d

**Comment by colin-nolan** [comment]
Issue not detected previously due to #16.

**Comment by irinaColgiu** [comment]
I think we should test the code also in production from now on. There seem to be rising quite a few issues due to the differences between the test environment and the production environment.
