### ISSUE TITLE
KeyError Exception thrown when calling irods.data_object.get_all_in_collection

### ISSUE THREAD

**Issue by irinaColgiu** [wtsi-hgi/python-baton-wrapper#23]
I don't see any obvious reason why this method call is throwing an exception, I just call it as suggested in readme:

In [19]: irods = connect_to_irods_with_baton("/path/to/baton-0.16.1/bin/", skip_baton_binaries_validation=True) # type: Connection
## In [20]: irods.data_object.get_all_in_collection('/humgen/projects/helic/')

KeyError                                  Traceback (most recent call last)
<ipython-input-20-dac8406ad48d> in <module>()
----> 1 irods.data_object.get_all_in_collection('/humgen/projects/helic/')

/nfs/users/nfs_i/ic4/Projects/python3/meta-check/ENV/lib/python3.5/site-packages/baton/_baton_mappers.py in get_all_in_collection(self, collection_paths, load_metadata)
    139             data_objects_as_baton_json += baton_item_as_json[BATON_COLLECTION_CONTENTS]
    140 
--> 141         return self._baton_json_to_irods_entities(data_objects_as_baton_json)
    142 
    143     def _path_to_baton_json(self, path: str) -> dict:

/nfs/users/nfs_i/ic4/Projects/python3/meta-check/ENV/lib/python3.5/site-packages/baton/_baton_mappers.py in _baton_json_to_irods_entities(self, entities_as_baton_json)
     89         entities = []
     90         for file_as_baton_json in entities_as_baton_json:
---> 91             entity = self._baton_json_to_irod_entity(file_as_baton_json)
     92             entities.append(entity)
     93 

/nfs/users/nfs_i/ic4/Projects/python3/meta-check/ENV/lib/python3.5/site-packages/baton/_baton_mappers.py in _baton_json_to_irod_entity(self, entity_as_baton_json)
    146 
    147     def _baton_json_to_irod_entity(self, entity_as_baton_json: dict) -> DataObject:
--> 148         return DataObjectJSONDecoder().decode_dict(entity_as_baton_json)
    149 
    150 

/nfs/users/nfs_i/ic4/Projects/python3/meta-check/ENV/lib/python3.5/site-packages/baton/json.py in decode_dict(self, json_as_dict)
    172 
    173     def decode_dict(self, json_as_dict: Dict):
--> 174         data_object = super().decode_dict(json_as_dict)
    175         timestamps_as_json = json_as_dict["timestamps"]
    176         DataObjectJSONDecoder._deserialize_timestamps_as_json(data_object, timestamps_as_json)

/nfs/users/nfs_i/ic4/Projects/python3/meta-check/ENV/lib/python3.5/site-packages/hgijson/json/_serialization.py in decode_dict(self, json_as_dict)
     91     def decode_dict(self, json_as_dict: dict) -> SerializableType:
     92         deserializer = self._create_deserializer()
---> 93         return deserializer.deserialize(json_as_dict)
     94 
     95     def _create_deserializer(self) -> JsonObjectDeserializer:

/nfs/users/nfs_i/ic4/Projects/python3/meta-check/ENV/lib/python3.5/site-packages/hgijson/serialization.py in deserialize(self, to_deserialize)
    113             for mapping in self._property_mappings:
    114                 if mapping.object_constructor_parameter_name is not None:
--> 115                     value = mapping.serialized_property_getter(to_deserialize)
    116                     if not (mapping.optional and value is None):
    117                         decoded_value = self._deserialize_property_value(value, mapping.deserializer_cls)

/nfs/users/nfs_i/ic4/Projects/python3/meta-check/ENV/lib/python3.5/site-packages/baton/json.py in <lambda>(json_as_dict)
    131     JsonPropertyMapping(None, "path", "path",
    132                         json_property_getter=lambda json_as_dict: json_as_dict[BATON_COLLECTION_PROPERTY]
--> 133                                                                   + "/" + json_as_dict[BATON_DATA_OBJECT_PROPERTY]),
    134     JsonPropertyMapping(BATON_COLLECTION_PROPERTY,
    135                         object_property_getter=lambda irods_entity: irods_entity.get_collection_path()),

KeyError: 'data_object'

**Comment by colin-nolan** [comment]
Looks like a bug :(. At a guess I'd say that it's tripping up by assuming everything inside the collection is going to be a data object. If there is a nested collection, it won't have the "data_object" value and would raise such an exception
