### ISSUE TITLE
Unclear documentation as to what baton.collections.Metadata.from_metadata is doing

### ISSUE THREAD

**Issue by irinaColgiu** [wtsi-hgi/python-baton-wrapper#24]
It is not clear to me what the difference between hgicommon.collections.Metadata and baton.collections.IrodsMetadata is, since there doesn't seem to be any no new data fields that one model contains and the other one doesn't.

The documentation below is slightly ambiguous as it is not clear what _this type_ in the context of "_equivalent  instance of this type_" is and it is also not clear to me as to why we need this conversion.

> Help on function from_metadata in module baton.collections:
> 
> from_metadata(metadata:hgicommon.collections.Metadata) -> typing.Any
>     Static factory method to create an equivalent instance of this type from the given `Metadata` instance.
>     :param metadata: the `Metadata` instance to create an instance of this class from
>     :return: the created instance of this class

**Comment by colin-nolan** [comment]
The difference is that `IrodsMetadata` ensures that keys are associated to sets of values, reflecting what is allowed in iRODS. The methods are subsequently more restrictive than that of the superclass, which allows keys to be associated to any value. The current implementation is essentially `Dict[str, Set[Any]]` (with convience methods).

**Comment by colin-nolan** [comment]
"this" in the docs for an instance method refers to the instabce; "this" in the docs for a class method refers to the class. Sorry if that's not clear.
