### ISSUE TITLE
IrodsMetadata.add() is not thread safe, though Metadata is

### ISSUE THREAD

**Issue by irinaColgiu** [wtsi-hgi/python-baton-wrapper#25]
It seems to me that even though Metadata is a thread-safe class, IrodsMetadata is not - at least judging by the IrodsMetadata.add() method:
https://github.com/wtsi-hgi/python-baton-wrapper/blob/master/baton/collections.py#L26-L36

which in the case of an existing key it reads the value of the existing value - which is a set of items - and adds the new value to the set without acquiring any lock. Nothing stops a different thread from modifying the same set of items at the same time, in which case one of the changes will be lost.

Speaking of thread-safety in Metadata class, I have the following questions/issues:
- do we really need a dict of Locks for the Metadata? Isn't it more clear, simple and elegant to have just 1 Lock for this class? A thread could acquire and block the whole Metadata object while modifying, instead of 1 thread acquiring X Locks and spending some time before the guarded block of code acquiring X locks, and then spending another amount of time releasing X Locks? It will use at least double the amount of memory because you keep 2 dicts instead of 1 with the same length. Though we are not short on memory in this case, I don't think this dict of Locks makes any improvement in terms of runtime, on the contrary, plus it adds quite a bit of complexity to the code
- when using CPython and multithreading you can't run multiple threads simultaneously anyway...
- is there any use-case in which multiple threads access the same global instance of metadata?

**Comment by irinaColgiu** [comment]
Actually, according to the documentation, despite the presence of GIL "multithreading is still an appropriate model if you want to run multiple I/O-bound tasks simultaneously."
Regarding the first bullet I've opened a new issue: #26

**Comment by colin-nolan** [comment]
`Metadata` ensures that operations that change the values associated to keys are atomic. It does not protect access to the content of non-primitive values. `add` changes the contents of a value, not what value is associated to the key.

I have exported your other questions/issues over to: https://github.com/wtsi-hgi/python-common/issues/8.
