### ISSUE TITLE
Change Metadata class to use 1 Lock because it is not thread safe with a non-safe dict of Locks

### ISSUE THREAD

**Issue by irinaColgiu** [wtsi-hgi/python-baton-wrapper#26]
I just realized that Metadata class is not thread-safe exactly because of the dict of Locks which is not thread-safe. You are making a dict-like structure thread-safe, with a non-safe dict...
What happens if 2 threads want to insert in the Metadata the same key (different values) for the first time? So thread1 reads the dict of Locks, sees that there is no Lock for KeyX and starts the procedure of creating a Lock. Meanwhile thread2 reads the dict of Locks, sees that there is no Lock for KeyX and starts the procedure of creating a Lock...They both obtain a Lock so they are both good to write to the Metadata._data...
And you are back to solving problem number 1..

**Comment by colin-nolan** [comment]
This issue relates to a different library. I have moved it to:
https://github.com/wtsi-hgi/python-common/issues/8
