### ISSUE TITLE
The zone of users referenced by access controls must be known

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/python-baton-wrapper#32]
Access controls currently only reference a user by their username. However, a username does not uniquely identify a user; for this, it is necessary to also know the zone of the user. It is therefore currently ambiguous as to which user an access control relates to.

This issue is linked to an issue with `baton-chmod` and its incorrect handling of zones:
https://github.com/wtsi-npg/baton/issues/156

**Comment by irinaColgiu** [comment]
I suggest adding an extra attribute to AccessControl class for the zone.

**Comment by colin-nolan** [comment]
I've fixed this issue by creating a model of a user:
https://github.com/wtsi-hgi/python-baton-wrapper/blob/fix/32-noUserZone/baton/models.py#L38

`AccessControl` has been changed so that it uses this model:
https://github.com/wtsi-hgi/python-baton-wrapper/blob/fix/32-noUserZone/baton/models.py#L82

The nice thing is that I've made this `User` model equivalent to the string representation "name#zone". Therefore it won't break any existing code, so long as you've been identifying users in this form (and not leaving it to baton/iRODS to use a undefined zone!) and you aren't been strict about the type. The API will accept both the `User` model and its string representation:
https://github.com/wtsi-hgi/python-baton-wrapper/blob/fix/32-noUserZone/baton/mappers.py#L102

For an updated example, see the README:
https://github.com/wtsi-hgi/python-baton-wrapper/tree/fix/32-noUserZone#access-control-lists-acls
