### ISSUE TITLE
BatonDataObjectMapper.metadata and access_control are defined as methods, but used as properties

### ISSUE THREAD

**Issue by irinaColgiu** [wtsi-hgi/python-baton-wrapper#40]
BatonDataObjectMapper.metadata and access_control are defined as methods here:

https://github.com/wtsi-hgi/python-baton-wrapper/blob/5197522430f83799f16a488341ba81d832c359ee/baton/_baton/baton_entity_mappers.py#L160

but then according to the readme, they should be used as properties:

irods.data_object.metadata.add("/collection/data_object", metadata_examples[0])

**Comment by colin-nolan** [comment]
The mapper interface defines that these should be properties:
https://github.com/wtsi-hgi/python-baton-wrapper/blob/master/baton/mappers.py#L166-L178

It's surpising that Python lets these unimplemented abstract properties slip (it must just see that a function implements it and that's good enough!).

**Comment by colin-nolan** [comment]
Test for existance of metadata property is incorrect:
https://github.com/wtsi-hgi/python-baton-wrapper/blob/5197522430f83799f16a488341ba81d832c359ee/baton/tests/_baton/test_baton_entity_mappers.py#L240-L241

No tests for access property property.
