### ISSUE TITLE
[..]access_control.revoke() expects a list of Users, but according to the docs takes in an ACL

### ISSUE THREAD

**Issue by irinaColgiu** [wtsi-hgi/python-baton-wrapper#42]
It seems to be a mismatch between the docs which state that "revoke" method accepts an AccessControl (or list of ACs):

``` python
irods.data_object.access_control.revoke(["/collection/data_object", "/another/data_object"], acl_examples)
```

and the actual code that accepts only Users -- the method signature is:

``` python
 def revoke(self, paths: Union[str, Iterable[str]], users: Union[str, Iterable[str], User, Iterable[User]]):
```

[taken from: https://github.com/wtsi-hgi/python-baton-wrapper/blob/master/baton/_baton/baton_access_control_mappers.py#L89]

(so when this function is called with [<path>, AccessControl] as parameters, one gets an error:

``` python
TypeError: object of type 'AccessControl' has no len()
```

because only the input parameters of type User are converted to list.)

I am not sure which option is better...
On one hand it makes sense for the second parameter to be an AccessControl, rather than a user,  just because it is more clear in terms of what ACL one refers to without a doubt....and because all the other methods take also AccessControls as parameters. Even though an AccessControl contains more information than needed. On the other hand, a client that know that he wants user X to have READ access would be obliged to fetch all the AccessControls first for that data object, search through the set of AccessControls to see if there is any AccessControl for user X, and then get that and put it as parameter for revoke method...

**Comment by colin-nolan** [comment]
As you point out, the develop shouldn't have to find out a user's permission before they can revoke them all.

The documentation is wrong in this case - I shall correct it now.

**Comment by irinaColgiu** [comment]
Yes, after giving it a second thought, I agree that the docs should be corrected, not the actual code.
